// Package docs GENERATED BY SWAG; DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "MentorHub Support",
            "email": "support@mentorhub.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {

        "/api/v1/auth/login": {
            "post": {
                "summary": "Вход в систему",
                "tags": ["auth"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["email", "password"],
                        "properties": {
                            "email":    { "type": "string", "example": "freshman1@mentorhub.com" },
                            "password": { "type": "string", "example": "password123" }
                        }
                    }
                }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/auth/register": {
            "post": {
                "summary": "Регистрация нового пользователя",
                "tags": ["auth"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["email", "password", "role", "first_name", "last_name"],
                        "properties": {
                            "email":      { "type": "string", "example": "newstudent@mentorhub.com" },
                            "password":   { "type": "string", "example": "password123" },
                            "role":       { "type": "string", "example": "freshman", "enum": ["head","advisor","mentor","freshman"] },
                            "first_name": { "type": "string", "example": "Иван" },
                            "last_name":  { "type": "string", "example": "Иванов" }
                        }
                    }
                }],
                "responses": { "201": { "description": "Created" } }
            }
        },

        "/api/v1/auth/refresh": {
            "post": {
                "summary": "Обновить access token",
                "tags": ["auth"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["refresh_token"],
                        "properties": {
                            "refresh_token": { "type": "string", "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..." }
                        }
                    }
                }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/auth/logout": {
            "post": {
                "summary": "Выход из системы",
                "tags": ["auth"],
                "security": [{ "BearerAuth": [] }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/auth/me": {
            "get": {
                "summary": "Профиль текущего пользователя",
                "tags": ["auth"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/freshman/dashboard": {
            "get": {
                "summary": "Дэшборд первокурсника",
                "tags": ["freshman"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/freshman/tasks": {
            "get": {
                "summary": "Задачи первокурсника",
                "tags": ["freshman"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/freshman/tasks/{id}": {
            "get": {
                "summary": "Детали конкретной задачи",
                "tags": ["freshman"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "parameters": [{ "name": "id", "in": "path", "required": true, "type": "string", "description": "Task UUID" }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/freshman/tasks/{id}/submit": {
            "put": {
                "summary": "Сдать задачу с решением",
                "tags": ["freshman"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "string", "description": "Task UUID" },
                    {
                        "name": "body", "in": "body", "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["proof_url"],
                            "properties": {
                                "proof_url": { "type": "string", "example": "https://portal.university.edu/proof.pdf" }
                            }
                        }
                    }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/freshman/meetings": {
            "get": {
                "summary": "Встречи группы первокурсника",
                "tags": ["freshman"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/freshman/announcements": {
            "get": {
                "summary": "Объявления группы",
                "tags": ["freshman"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/freshman/faq": {
            "get": {
                "summary": "Список FAQ вопросов",
                "tags": ["freshman"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/freshman/notifications": {
            "get": {
                "summary": "Уведомления первокурсника",
                "tags": ["freshman"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/freshman/notifications/read-all": {
            "put": {
                "summary": "Отметить все уведомления как прочитанные",
                "tags": ["freshman"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/freshman/notifications/{id}/read": {
            "put": {
                "summary": "Отметить уведомление как прочитанное",
                "tags": ["freshman"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "parameters": [{ "name": "id", "in": "path", "required": true, "type": "string", "description": "Notification UUID" }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/freshman/questions": {
            "get": {
                "summary": "Мои вопросы ментору",
                "tags": ["freshman"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            },
            "post": {
                "summary": "Задать вопрос ментору",
                "tags": ["freshman"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["body"],
                        "properties": {
                            "body": { "type": "string", "example": "Во сколько завтра встреча?" }
                        }
                    }
                }],
                "responses": { "201": { "description": "Created" } }
            }
        },

        "/api/v1/mentor/dashboard": {
            "get": {
                "summary": "Дэшборд ментора",
                "tags": ["mentor"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/mentor/group": {
            "get": {
                "summary": "Список первокурсников в группе ментора",
                "tags": ["mentor"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/mentor/group/{id}": {
            "get": {
                "summary": "Детали первокурсника и его задачи",
                "tags": ["mentor"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "parameters": [{ "name": "id", "in": "path", "required": true, "type": "string", "description": "Freshman UUID" }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/mentor/tasks": {
            "get": {
                "summary": "Задачи студентов группы ментора",
                "tags": ["mentor"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "parameters": [{ "name": "status", "in": "query", "required": false, "type": "string", "description": "Фильтр: pending|submitted|approved|rejected" }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/mentor/tasks/{id}/approve": {
            "put": {
                "summary": "Принять сданную задачу студента",
                "tags": ["mentor"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "string", "description": "Task UUID" },
                    {
                        "name": "body", "in": "body", "required": false,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "comment": { "type": "string", "example": "Отличная работа!" }
                            }
                        }
                    }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/mentor/tasks/{id}/reject": {
            "put": {
                "summary": "Отклонить сданную задачу с комментарием",
                "tags": ["mentor"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "string", "description": "Task UUID" },
                    {
                        "name": "body", "in": "body", "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["comment"],
                            "properties": {
                                "comment": { "type": "string", "example": "Пересдайте в лучшем качестве" }
                            }
                        }
                    }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/mentor/meetings": {
            "get": {
                "summary": "Список встреч ментора",
                "tags": ["mentor"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            },
            "post": {
                "summary": "Запланировать встречу",
                "tags": ["mentor"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["title", "scheduled_at"],
                        "properties": {
                            "title":        { "type": "string", "example": "Еженедельная встреча" },
                            "description":  { "type": "string", "example": "Обсуждение прогресса" },
                            "scheduled_at": { "type": "string", "format": "date-time", "example": "2026-09-01T15:00:00Z" }
                        }
                    }
                }],
                "responses": { "201": { "description": "Created" } }
            }
        },

        "/api/v1/mentor/meetings/{id}/complete": {
            "put": {
                "summary": "Завершить встречу и добавить заметки",
                "tags": ["mentor"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "string", "description": "Meeting UUID" },
                    {
                        "name": "body", "in": "body", "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "notes": { "type": "string", "example": "Обсудили план на следующую неделю" }
                            }
                        }
                    }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/mentor/announcements": {
            "get": {
                "summary": "Список объявлений группы",
                "tags": ["mentor"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            },
            "post": {
                "summary": "Опубликовать объявление для группы",
                "tags": ["mentor"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["title", "body"],
                        "properties": {
                            "title":    { "type": "string", "example": "Важное объявление" },
                            "body":     { "type": "string", "example": "Завтра встреча перенесена на 16:00" },
                            "group_id": { "type": "string", "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6" }
                        }
                    }
                }],
                "responses": { "201": { "description": "Created" } }
            }
        },

        "/api/v1/mentor/questions": {
            "get": {
                "summary": "Вопросы от первокурсников",
                "tags": ["mentor"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/mentor/questions/{id}/answer": {
            "put": {
                "summary": "Ответить на вопрос первокурсника",
                "tags": ["mentor"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "string", "description": "Question UUID" },
                    {
                        "name": "body", "in": "body", "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["answer"],
                            "properties": {
                                "answer": { "type": "string", "example": "Встреча состоится в 15:00 в 302 кабинете" }
                            }
                        }
                    }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/advisor/dashboard": {
            "get": {
                "summary": "Дэшборд эдвайзера",
                "tags": ["advisor"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/advisor/mentors": {
            "get": {
                "summary": "Список менторов со статистикой",
                "tags": ["advisor"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/advisor/mentors/{id}/students": {
            "get": {
                "summary": "Список студентов конкретного ментора",
                "tags": ["advisor"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "parameters": [{ "name": "id", "in": "path", "required": true, "type": "string", "description": "Mentor UUID" }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/advisor/mentors/{id}/tasks": {
            "get": {
                "summary": "Прогресс по задачам студентов ментора",
                "tags": ["advisor"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "string", "description": "Mentor UUID" },
                    { "name": "status", "in": "query", "required": false, "type": "string", "description": "Фильтр: pending|submitted|approved|rejected" }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/advisor/inactive-students": {
            "get": {
                "summary": "Неактивные студенты (без сабмитов за N дней)",
                "tags": ["advisor"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "parameters": [{ "name": "days", "in": "query", "required": false, "type": "integer", "description": "Количество дней (default: 7)" }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/advisor/reminders": {
            "post": {
                "summary": "Отправить напоминание ментору или студенту",
                "tags": ["advisor"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["target_id", "message"],
                        "properties": {
                            "target_id": { "type": "string", "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6" },
                            "message":   { "type": "string", "example": "Не забудьте сдать задачу до пятницы" }
                        }
                    }
                }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/advisor/complaints": {
            "post": {
                "summary": "Подать жалобу",
                "tags": ["advisor"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["against_id", "description"],
                        "properties": {
                            "against_id":  { "type": "string", "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6" },
                            "description": { "type": "string", "example": "Ментор не выходит на связь уже неделю" }
                        }
                    }
                }],
                "responses": { "201": { "description": "Created" } }
            }
        },

        "/api/v1/advisor/analytics": {
            "get": {
                "summary": "Аналитика эдвайзера",
                "tags": ["advisor"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/head/dashboard": {
            "get": {
                "summary": "Дэшборд руководителя (Head)",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/head/users": {
            "get": {
                "summary": "Список всех пользователей в системе",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "role",     "in": "query", "required": false, "type": "string",  "description": "Фильтр по роли: advisor|mentor|freshman" },
                    { "name": "page",     "in": "query", "required": false, "type": "integer", "description": "Страница (default: 1)" },
                    { "name": "per_page", "in": "query", "required": false, "type": "integer", "description": "Размер страницы (default: 20)" }
                ],
                "responses": { "200": { "description": "OK" } }
            },
            "post": {
                "summary": "Создать пользователя",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["email", "password", "role", "first_name", "last_name"],
                        "properties": {
                            "email":      { "type": "string", "example": "mentor1@mentorhub.com" },
                            "password":   { "type": "string", "example": "password123" },
                            "role":       { "type": "string", "example": "mentor", "enum": ["advisor","mentor","freshman"] },
                            "first_name": { "type": "string", "example": "Алексей" },
                            "last_name":  { "type": "string", "example": "Петров" }
                        }
                    }
                }],
                "responses": { "201": { "description": "Created" } }
            }
        },

        "/api/v1/head/users/{id}/deactivate": {
            "put": {
                "summary": "Деактивировать пользователя",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "parameters": [{ "name": "id", "in": "path", "required": true, "type": "string", "description": "User UUID" }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/head/users/{id}": {
            "delete": {
                "summary": "Удалить пользователя",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [{ "name": "id", "in": "path", "required": true, "type": "string", "description": "User UUID" }],
                "responses": { "204": { "description": "No Content" } }
            }
        },

        "/api/v1/head/academic-years": {
            "get": {
                "summary": "Список учебных годов",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            },
            "post": {
                "summary": "Создать учебный год",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["name", "start_date", "end_date"],
                        "properties": {
                            "name":       { "type": "string", "example": "2026-2027" },
                            "start_date": { "type": "string", "format": "date-time", "example": "2026-09-01T00:00:00Z" },
                            "end_date":   { "type": "string", "format": "date-time", "example": "2027-06-30T00:00:00Z" }
                        }
                    }
                }],
                "responses": { "201": { "description": "Created" } }
            }
        },

        "/api/v1/head/academic-years/{id}/activate": {
            "put": {
                "summary": "Сделать учебный год активным",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "parameters": [{ "name": "id", "in": "path", "required": true, "type": "string", "description": "AcademicYear UUID" }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/head/faculties": {
            "get": {
                "summary": "Факультеты и специальности",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            },
            "post": {
                "summary": "Создать факультет",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["name", "code"],
                        "properties": {
                            "name": { "type": "string", "example": "Информационные технологии" },
                            "code": { "type": "string", "example": "IT" }
                        }
                    }
                }],
                "responses": { "201": { "description": "Created" } }
            }
        },

        "/api/v1/head/specialties": {
            "post": {
                "summary": "Создать специальность",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["faculty_id", "name"],
                        "properties": {
                            "faculty_id": { "type": "string", "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6" },
                            "name":       { "type": "string", "example": "Программная инженерия" }
                        }
                    }
                }],
                "responses": { "201": { "description": "Created" } }
            }
        },

        "/api/v1/head/assign/mentor": {
            "post": {
                "summary": "Назначить ментора к эдвайзеру",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["mentor_id", "advisor_id"],
                        "properties": {
                            "mentor_id":  { "type": "string", "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6" },
                            "advisor_id": { "type": "string", "example": "5a8b3c21-1234-4321-bcde-1a2b3c4d5e6f" }
                        }
                    }
                }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/head/task-templates": {
            "get": {
                "summary": "Список шаблонов задач",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "parameters": [{ "name": "active_only", "in": "query", "required": false, "type": "boolean", "description": "Только активные" }],
                "responses": { "200": { "description": "OK" } }
            },
            "post": {
                "summary": "Создать шаблон задачи",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "body", "in": "body", "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["title", "due_days"],
                        "properties": {
                            "title":       { "type": "string",  "example": "Пройти онбординг" },
                            "description": { "type": "string",  "example": "Ознакомиться с материалами" },
                            "due_days":    { "type": "integer", "example": 7 }
                        }
                    }
                }],
                "responses": { "201": { "description": "Created" } }
            }
        },

        "/api/v1/head/task-templates/{id}": {
            "put": {
                "summary": "Обновить шаблон задачи",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "string", "description": "Template UUID" },
                    {
                        "name": "body", "in": "body", "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "title":       { "type": "string",  "example": "Обновлённое название" },
                                "description": { "type": "string",  "example": "Обновлённое описание" },
                                "due_days":    { "type": "integer", "example": 14 },
                                "is_active":   { "type": "boolean", "example": true }
                            }
                        }
                    }
                ],
                "responses": { "200": { "description": "OK" } }
            },
            "delete": {
                "summary": "Удалить шаблон задачи",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "parameters": [{ "name": "id", "in": "path", "required": true, "type": "string", "description": "Template UUID" }],
                "responses": { "204": { "description": "No Content" } }
            }
        },

        "/api/v1/head/task-templates/{id}/assign": {
            "post": {
                "summary": "Массово назначить шаблон задачи первокурсникам",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "string", "description": "Template UUID" },
                    {
                        "name": "body", "in": "body", "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["freshman_ids"],
                            "properties": {
                                "freshman_ids": { "type": "array", "items": { "type": "string" }, "example": ["3fa85f64-5717-4562-b3fc-2c963f66afa6"] },
                                "due_date":     { "type": "string", "format": "date-time", "example": "2026-09-15T00:00:00Z" }
                            }
                        }
                    }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/head/analytics": {
            "get": {
                "summary": "Общая аналитика системы",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/head/complaints": {
            "get": {
                "summary": "Список жалоб",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "parameters": [{ "name": "status", "in": "query", "required": false, "type": "string", "description": "Фильтр: open|in_review|resolved|dismissed" }],
                "responses": { "200": { "description": "OK" } }
            }
        },

        "/api/v1/head/complaints/{id}": {
            "put": {
                "summary": "Обновить статус жалобы",
                "tags": ["head"],
                "security": [{ "BearerAuth": [] }],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "id", "in": "path", "required": true, "type": "string", "description": "Complaint UUID" },
                    {
                        "name": "body", "in": "body", "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["status"],
                            "properties": {
                                "status": { "type": "string", "example": "resolved", "enum": ["in_review","resolved","dismissed"] }
                            }
                        }
                    }
                ],
                "responses": { "200": { "description": "OK" } }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8088",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "MentorHub Backend API",
	Description:      "MentorHub REST API specification for Head, Advisor, Mentor, and Freshman roles.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}

